name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # uses v3 Stable version
    # https://github.com/actions/checkout
    - name: checkout source
      uses: actions/checkout@v3
    # Build Artifacts
    - name: Build Book file
      uses: hitsumabushi845/ReVIEW-build-artifact-action@master
    # Fetch Book title
    - name: Fetch book title
      id: bookTitle
      uses: mikefarah/yq@master
      with:
        cmd: yq '.bookname' 'articles/config.yml'
    # Upload Distribution file
    - name: Upload distribution file to github artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.bookTitle.outputs.result }}
        path: ./articles/*.pdf
